name: CI
'on':
    push:
        branches:
            - master
            - develop
    pull_requests:
        branches:
            - master
            - develop
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install
            - run: yarn format
            - run: yarn lint
            - run: yarn type
            - run: yarn build
