name: Deploy
'on':
    push:
        branches:
            - master
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            name: Deploy using ssh
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                port: 22
                script: |
                    cd ~/home/sf/stackforce-frontend
                    git checkout master
                    git pull
                    git status
                    yarn install
                    pm2 restart sf-front
                    - 
